// Code generated by go-swagger; DO NOT EDIT.

// Package acr ACRCloud Webhooks Receiver
//
//  Hooks to receive ACRCloud events on and a simple API to query the received data.
//  Stores all data in a PostgreSQL database for later querying.
//
//  Schemes:
//    http
//    https
//  Host: localhost
//  BasePath: /
//  Version: 0.1.0
//  License: AGPLv3 https://www.gnu.org/licenses/agpl-3.0.en.html
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package acr
