// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Contributors contributors
//
// swagger:model Contributors
type Contributors struct {

	// composers
	Composers []string `json:"composers"`

	// lyricists
	Lyricists []string `json:"lyricists"`
}

// Validate validates this contributors
func (m *Contributors) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Contributors) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Contributors) UnmarshalBinary(b []byte) error {
	var res Contributors
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
