// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ExternalIds external ids
//
// swagger:model ExternalIds
type ExternalIds struct {

	// deezer
	Deezer string `json:"deezer,omitempty"`

	// isrc
	Isrc interface{} `json:"isrc,omitempty"`

	// itunes
	Itunes string `json:"itunes,omitempty"`

	// lyricfind
	Lyricfind string `json:"lyricfind,omitempty"`

	// musicstory
	Musicstory string `json:"musicstory,omitempty"`

	// spotify
	Spotify string `json:"spotify,omitempty"`

	// upc
	Upc interface{} `json:"upc,omitempty"`

	// youtube
	Youtube string `json:"youtube,omitempty"`
}

// Validate validates this external ids
func (m *ExternalIds) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this external ids based on context it is used
func (m *ExternalIds) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ExternalIds) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExternalIds) UnmarshalBinary(b []byte) error {
	var res ExternalIds
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
