// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RightsOwner rights owner
//
// swagger:model RightsOwner
type RightsOwner struct {

	// name
	Name string `json:"name,omitempty"`

	// share percentage
	SharePercentage string `json:"share_percentage,omitempty"`
}

// Validate validates this rights owner
func (m *RightsOwner) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RightsOwner) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RightsOwner) UnmarshalBinary(b []byte) error {
	var res RightsOwner
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
