// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// Time time
//
// swagger:model Time
type Time int64

// Validate validates this time
func (m Time) Validate(formats strfmt.Registry) error {
	return nil
}
